repos:
  # Tests automáticos antes de commit
  - repo: local
    hooks:
      - id: pytest
        name: Run tests
        entry: bash
        language: system
        args: [-c, 'source venv/bin/activate && TESTING=true ENABLE_ANALYTICS=false pytest tests/ --cov=app --cov-fail-under=48 -v --ignore=tests/test_analytics_endpoints.py --ignore=tests/test_auth_endpoints.py']
        pass_filenames: false
        always_run: true
      
      - id: security-scan
        name: Security scan
        entry: bash
        language: system
        args: [-c, 'bandit -r app/ -f json -o bandit-report.json || echo "Security issues found"']
        pass_filenames: false
        always_run: true

  # Linting y formateo
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       args: [--max-line-length=150, --ignore=E203,W503,E501,E402,F541,F841,E226]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile=black]

  # Verificar dependencias vulnerables (deshabilitado temporalmente)
  # - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
  #   rev: v1.3.2
  #   hooks:
  #     - id: python-safety-dependencies-check
  #       args: [--file=requirements.txt]
